# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

WORKDIR /imager

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y curl
EXPOSE 5050

COPY ./file_server .

# CMD [ "flask", "run" ]