services:
  imager-app:
    build:
      context: ../com3014_image_storage
      dockerfile: Dockerfile.imager
    command: python -u main.py
    ports:
      - "5050:5050"
    volumes:
      - ./file_server:/imager
    links:
      - imager-db
    networks:
      - image-net
  imager-db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=com3014_images
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - image-net
networks:
  image-net:
    driver: bridge